/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-05-20 04:34:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import db.fun.*;
import db.pojo.*;
import struts.UserVote.*;

public final class chooseAdmin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />。\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <meta name=\"description\" content=\"\">\n");
      out.write("    <meta name=\"author\" content=\"\">\n");
      out.write("    <title>管理员功能选择</title>\n");
      out.write("    <!-- Bootstrap -->\n");
      out.write("    <link href=\"css/bootstrap.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"css/bootstrap-theme.css\" rel=\"stylesheet\">\n");
      out.write("    <!-- siimple style -->\n");
      out.write("    <link href=\"css/style.css\" rel=\"stylesheet\">\n");
      out.write("        <style type=\"text/css\">\n");
      out.write("    body {\n");
      out.write("        background-color: #f6f6f6;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    #logo-text,\n");
      out.write("    #login {\n");
      out.write("        color: #ffffff;\n");
      out.write("        font-size: 20px;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    #logo {\n");
      out.write("        padding-top: 5px;\n");
      out.write("    }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("    <!-- Fixed navbar -->\n");
      out.write("    <div class=\"navbar navbar-inverse navbar-fixed-top\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"navbar-header\">\n");
      out.write("                <a class=\"navbar-brand\" id=\"logo\" href=\"index.jsp\"><img src=\"images/logo.png\" weight=\"48px\" height=\"48px\" /></a>\n");
      out.write("                <p class=\"navbar-text\" id=\"logo-text\">InnovationCamp</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"navbar-collapse collapse\">\n");
      out.write("                <ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("                    <li><a href=\"loginAdmin.jsp\" id=\"login\">login in</a></li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    ");
 if(session.getAttribute( "username") == null ){ 
      out.write("\n");
      out.write("    <div class=\"col-lg-4 col-lg-offset-4\">\n");
      out.write("    \t<h1>管理员未登录</h1>\n");
      out.write("    \t<a href=\"loginAdmin.jsp\">重新登录</a>\n");
      out.write("      ");
 }  else{
      out.write("\n");
      out.write("     \n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <div id=\"header\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-4\"> <img src=\"images/bg.jpg\" height=\"500px\" width=\"750px\" float=\"right\" /></div>\n");
      out.write("                <div class=\"col-lg-4 col-lg-offset-4\">\n");
      out.write("                    <h1>管理员功能选择</h1>\n");
      out.write("                    <h2 class=\"subtitle\">Vote for InnovationCamp</h2>\n");
      out.write("                    <br/>\n");
      out.write("                    <button type=\"button\" class=\"btn btn-info btn-block btn-lg\" onclick=\"window.location.href='loginwithcard.jsp'\">刷卡登陆</button>\n");
      out.write("                    <br/>\n");
      out.write("                    <button type=\"button\" class=\"btn btn-info btn-block btn-lg\" onclick=\"window.location.href='loginwithoutcard.html'\">无卡登陆</button>\n");
      out.write("                    <br/>\n");
      out.write("                    <button type=\"button\" class=\"btn btn-info btn-block btn-lg\" onclick=\"window.location.href='loginuser.jsp'\">删除选票</button>\n");
      out.write("                    <br/>\n");
      out.write("                    <button type=\"button\" class=\"btn btn-info btn-block btn-lg\" onclick=\"window.location.href='lottery.jsp'\">抽奖</button>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    ");
 }  
      out.write("\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-1.10.2.min.js\"></script>\n");
      out.write("    <script src=\"assets/js/bootstrap.min.js\"></script>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
