/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-05-17 11:15:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import db.fun.*;
import db.pojo.*;
import struts.UserVote.*;

public final class head_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=GBK");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("        <html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <head>\r\n");
      out.write("            ");
 FunVoteRecord record=null; 
      out.write("\r\n");
      out.write("        </head>\r\n");
      out.write("        <title> 删除界面 </title>\r\n");
      out.write("        <div align=\"center\">\r\n");
      out.write("            <table width=\"600\" border=\"1\" cellpadding=\"0\" cellspacing=\"0\" bordercolor=\"#00CCFF\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td height=\"20\" align=\"center\">\r\n");
      out.write("                        <form action=\"Loginout\" method=\"post\">\r\n");
      out.write("                            ");
 if(session.getAttribute( "username")==null || session.getAttribute( "username")=="" ){ 
      out.write("\r\n");
      out.write("                                未登录， <a href=\"login2.jsp\">登陆</a>\r\n");
      out.write("                                ");
 } else { String Username=session.getAttribute( "username").toString(); String UserNo=session.getAttribute( "UserNo").toString(); out.println(Username); out.println(UserNo); 
      out.write("\r\n");
      out.write("                                    <input type=\"hidden\" name=\"username\" value=\"");
      out.print(Username );
      out.write("\" />\r\n");
      out.write("                                    <input type=\"hidden\" name=\"UsreNo\" value=\"");
      out.print(UserNo );
      out.write("\" />\r\n");
      out.write("                                    <input type=\"submit\" value=\"退出\" />\r\n");
      out.write("                        </form>\r\n");
      out.write("                        <form action=\"DeleteVote\" method=\"post\">\r\n");
      out.write("                            ");
 List list=new FunUserData().userVote(UserNo); 
      out.write("\r\n");
      out.write("                                ");
 for(int i=0; i<list.size();i++) { 
      out.write("\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <input type=\"radio\" name=\"ProjectID\" value=\"");
      out.print(((VoteRecord)list.get(i)).getProjectID() );
      out.write("\" check=\"checked\">\r\n");
      out.write("                                        ");
      out.print(((VoteRecord)list.get(i)).getProjectID() );
      out.write("\r\n");
      out.write("                                            </label>\r\n");
      out.write("                                    </td>\r\n");
      out.write("\r\n");
      out.write("                                    ");
 } 
      out.write("\r\n");
      out.write("                                        <input type=\"hidden\" name=\"UserNo\" value=\"");
      out.print(UserNo );
      out.write("\" />\r\n");
      out.write("                                        ");
      out.print(UserNo );
      out.write("\r\n");
      out.write("                                            <input type=\"submit\" />\r\n");
      out.write("                       \r\n");
      out.write("                        ");
} 
      out.write("\r\n");
      out.write(" </form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        </body>\r\n");
      out.write("\r\n");
      out.write("        </html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
