/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2016-05-17 02:56:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005ffielderror_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fs_005ffielderror_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fs_005ffielderror_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html lang=\"en\">\r\n");
      out.write("<!-- \r\n");
      out.write(" -->\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <meta name=\"description\" content=\"\">\r\n");
      out.write("  <meta name=\"author\" content=\"\">\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <title>大创提交系统</title>\r\n");
      out.write("  <!-- Bootstrap -->\r\n");
      out.write("  <link href=\"css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"css/bootstrap-theme.css\" rel=\"stylesheet\">\r\n");
      out.write("  <!-- siimple style -->\r\n");
      out.write("  <link href=\"css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("  <link href=\"css/templatemo_style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("  <link href=\"css/vegas.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("  <style type=\"text/css\">\r\n");
      out.write("  body {\r\n");
      out.write("    background-color: #f6f6f6;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  #logo-text,\r\n");
      out.write("  #login {\r\n");
      out.write("    color: #ffffff;\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  #logo {\r\n");
      out.write("    padding-top: 5px;\r\n");
      out.write("  }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"templatemo-bg-gray\">\r\n");
      out.write("  <!-- Fixed navbar -->\r\n");
      out.write("  <nav class=\"navbar navbar-inverse navbar-fixed-top\" role=\"navigation\">\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("      <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#example-navbar-collapse\">\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("      </button>\r\n");
      out.write("      <a class=\"navbar-brand\" id=\"logo\" href=\"index.jsp\"><img src=\"images/logo.png\" weight=\"48px\" height=\"48px\" /></a>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>\r\n");
      out.write("  <br/>\r\n");
      out.write("  <br/>\r\n");
      out.write("  <br/>\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <div class=\"col-lg-12\">\r\n");
      out.write("\r\n");
      out.write("      <form class=\"form-horizontal templatemo-container templatemo-login-form-1 margin-bottom-30\" role=\"form\" action=\"login\" method=\"post\">\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("          <div class=\"col-lg-12\">\r\n");
      out.write("          <h1 class=\"margin-bottom-15\">大创项目提交系统</h1>\r\n");
      out.write("            <div class=\"control-wrapper\">\r\n");
      out.write("              <label for=\"username\" class=\"control-label fa-label\"><i class=\"fa fa-user fa-medium\"></i></label>\r\n");
      out.write("              <input type=\"text\" class=\"form-control\" id=\"username\" placeholder=\"项目ID\" name=\"username\">\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("          <div class=\"col-lg-12\">\r\n");
      out.write("            <div class=\"control-wrapper\">\r\n");
      out.write("              <label for=\"password\" class=\"control-label fa-label\"><i class=\"fa fa-lock fa-medium\"></i></label>\r\n");
      out.write("              <input type=\"password\" class=\"form-control\" id=\"password\" placeholder=\"密码\" name=\"password\">\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("          <div class=\"col-lg-10\">\r\n");
      out.write("            <div class=\"control-wrapper col-md-offset-1\">\r\n");
      out.write("              ");
      if (_jspx_meth_s_005ffielderror_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <hr/>\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("          <div class=\"col-lg-8\">\r\n");
      out.write("            <div class=\"control-wrapper col-md-offset-5\">\r\n");
      out.write("              <input type=\"submit\" value=\"登录\" class=\"btn btn-info btn-block\">\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"modal fade\" id=\"lottery-modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <div class=\"modal-header\">\r\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">\r\n");
      out.write("            &times;\r\n");
      out.write("          </button>\r\n");
      out.write("          <h4 class=\"modal-title\" id=\"myModalLabel\">\r\n");
      out.write("              抽奖\r\n");
      out.write("           </h4>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-body\" style=\"overflow: hidden\">\r\n");
      out.write("          <div class=\"col-lg-12\">\r\n");
      out.write("            <form id=\"form\" class=\"form-horizontal\" role=\"form\">\r\n");
      out.write("              <div id=\"lottery-user\" class=\"form-group\">\r\n");
      out.write("                <label class=\"col-sm-2 control-label\">用户名</label>\r\n");
      out.write("                <div class=\"col-sm-10\">\r\n");
      out.write("                  <input class=\"textin form-control\" type=\"text\" placeholder=\"用户名\">\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div id=\"lottery-psw\" class=\"form-group\">\r\n");
      out.write("                <label class=\"col-sm-2 control-label\">密码</label>\r\n");
      out.write("                <div class=\"col-sm-10\">\r\n");
      out.write("                  <input class=\"textin form-control\" type=\"text\" placeholder=\"密码\">\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div id=\"lottery-check\" class=\"form-group\">\r\n");
      out.write("                <label class=\"col-sm-2 control-label\">验证码</label>\r\n");
      out.write("                <div class=\"col-sm-8\">\r\n");
      out.write("                  <input class=\"textin form-control\" type=\"text\" placeholder=\"验证码\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- <div class=\"col-sm-2\"><img src=\"\" style=\"width: 100%\"></div> -->\r\n");
      out.write("              </div>\r\n");
      out.write("            </form>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-footer\">\r\n");
      out.write("          <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">关闭\r\n");
      out.write("          </button>\r\n");
      out.write("          <button type=\"button\" class=\"btn btn-primary\" data-toggle=\"modal\">\r\n");
      out.write("            抽奖\r\n");
      out.write("          </button>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!--lottery-result-->\r\n");
      out.write("  <div class=\"modal fade\" id=\"lottery-result\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <div class=\"modal-header\">\r\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">\r\n");
      out.write("            &times;\r\n");
      out.write("          </button>\r\n");
      out.write("          <h4 class=\"modal-title\" id=\"myModalLabel\">\r\n");
      out.write("              抽奖结果\r\n");
      out.write("           </h4>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-body\" style=\"overflow: hidden\">\r\n");
      out.write("          <div class=\"col-lg-12 success\">\r\n");
      out.write("            <div>\r\n");
      out.write("              恭喜你抽中<span id=\"lo-result\"></span>等奖!\r\n");
      out.write("            </div>\r\n");
      out.write("            <label class=\"col-sm-4 address-lab\">请填写收货地址：</label>\r\n");
      out.write("            <div class=\"col-sm-8 address\">\r\n");
      out.write("              <input class=\"textin form-control\" type=\"text\" placeholder=\"收货地址\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div style=\"color: red;\">\r\n");
      out.write("              请认真填写，只有这一次机会！\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"fail\">\r\n");
      out.write("            很遗憾你没抽中，再接再厉~\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-footer\">\r\n");
      out.write("          <button type=\"button\" class=\"btn btn-default closeUp\" data-dismiss=\"modal\">关闭\r\n");
      out.write("          </button>\r\n");
      out.write("          <button type=\"button\" class=\"btn btn-default lotteryUp\">提交\r\n");
      out.write("          </button>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <script src=\"http://apps.bdimg.com/libs/jquery/1.11.3/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"js/vegas.min.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"js/mock.js\"></script>\r\n");
      out.write("  <script src=\"js/index.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\">\r\n");
      out.write("  $(document).ready(function() {\r\n");
      out.write("    $('body').vegas({\r\n");
      out.write("      slides: [{\r\n");
      out.write("        src: \"images/BG1.jpg\"\r\n");
      out.write("      }, {\r\n");
      out.write("        src: \"images/BG2.jpg\"\r\n");
      out.write("      }, {\r\n");
      out.write("        src: \"images/BG3.jpg\"\r\n");
      out.write("      }, {\r\n");
      out.write("        src: \"images/BG4.jpg\"\r\n");
      out.write("      }],\r\n");
      out.write("      timer: false,\r\n");
      out.write("      transition: 'random',\r\n");
      out.write("      delay: 6000\r\n");
      out.write("    })\r\n");
      out.write("  })\r\n");
      out.write("  </script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_s_005ffielderror_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:fielderror
    org.apache.struts2.views.jsp.ui.FieldErrorTag _jspx_th_s_005ffielderror_005f0 = (org.apache.struts2.views.jsp.ui.FieldErrorTag) _005fjspx_005ftagPool_005fs_005ffielderror_005fnobody.get(org.apache.struts2.views.jsp.ui.FieldErrorTag.class);
    _jspx_th_s_005ffielderror_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005ffielderror_005f0.setParent(null);
    int _jspx_eval_s_005ffielderror_005f0 = _jspx_th_s_005ffielderror_005f0.doStartTag();
    if (_jspx_th_s_005ffielderror_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005ffielderror_005fnobody.reuse(_jspx_th_s_005ffielderror_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005ffielderror_005fnobody.reuse(_jspx_th_s_005ffielderror_005f0);
    return false;
  }
}
