/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2016-05-17 14:55:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import db.fun.*;
import db.pojo.*;
import struts.ShowProjectOnlyAction;

public final class project_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\t");
 String path=request.getContextPath(); String basePath=request.getScheme()+ "://"+request.getServerName()+ ":"+request.getServerPort()+path+ "/"; 
      out.write("\r\n");
      out.write("  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <meta name=\"description\" content=\"\">\r\n");
      out.write("  <meta name=\"author\" content=\"\">\r\n");
      out.write("  <title>大创展投票系统</title>\r\n");
      out.write("  <!-- Bootstrap -->\r\n");
      out.write("  <link href=\"css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"css/bootstrap-theme.css\" rel=\"stylesheet\">\r\n");
      out.write("  <!-- simple style -->\r\n");
      out.write("  <link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/projectDetail.css\">\r\n");
      out.write("  <style type=\"text/css\">\r\n");
      out.write("  body {\r\n");
      out.write("    background-color: #f6f6f6;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  #logo-text,\r\n");
      out.write("  #login {\r\n");
      out.write("    color: #ffffff;\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  #logo {\r\n");
      out.write("    padding-top: 5px;\r\n");
      out.write("  }\r\n");
      out.write("  </style>\r\n");
      out.write("  <script src=\"http://apps.bdimg.com/libs/jquery/1.11.3/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("  <script src=\"js/mock.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("  <!-- Fixed navbar -->\r\n");
      out.write("  <nav class=\"navbar navbar-inverse navbar-fixed-top\" role=\"navigation\">\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("      <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#example-navbar-collapse\">\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("      </button>\r\n");
      out.write("      <a class=\"navbar-brand\" id=\"logo\" href=\"index.jsp\"><img src=\"images/logo.png\" weight=\"48px\" height=\"48px\" /></a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"example-navbar-collapse\">\r\n");
      out.write("      <ul class=\"nav navbar-nav\">\r\n");
      out.write("        <li><a href=\"#\" onclick=\"window.location.href='projectSearch.action'\">所有项目</a></li>\r\n");
      out.write("        <li><a href=\"#\" data-toggle=\"modal\" data-target=\"#lottery-modal\">我要抽奖</a></li>\r\n");
      out.write("        <!--<li><a href=\"#\">项目列表</a></li>-->\r\n");
      out.write("      </ul>\r\n");
      out.write("      <form class=\"navbar-form navbar-left\" role=\"search\" action=\"project\" method=\"POST\">\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("          <input type=\"text\" class=\"form-control\" placeholder=\"搜索项目ID\" name=\"projectID\">\r\n");
      out.write("          <button type=\"submit\" class=\"btn btn-default\">走你</button>\r\n");
      out.write("        </div>\r\n");
      out.write("      </form>\r\n");
      out.write("      <ul class=\"nav navbar-nav navbar-right\" style=\"margin-right: 20px\">\r\n");
      out.write("        <li><a href=\"login.jsp\" id=\"login\">我要提交项目</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>\r\n");
      out.write("  <!--project-detail-->\r\n");
      out.write("  <div class=\"container\" id=\"project-detail\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("      <div class=\"col-md-8 project-detail-img-box\">\r\n");
      out.write("      \t<span class=\"detail-img-src\" style=\"display: none\">");
      if (_jspx_meth_s_005fproperty_005f0(_jspx_page_context))
        return;
      out.write("</span>\r\n");
      out.write("        <img src=\"\" alt=\"\" class=\"img-responsive\" style=\"width: 100%;\">\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-md-4\">\r\n");
      out.write("        <h1 class=\"project-title\">");
      if (_jspx_meth_s_005fproperty_005f1(_jspx_page_context))
        return;
      out.write("</h1>\r\n");
      out.write("        <div class=\"partner\">\r\n");
      out.write("          <p><span class=\"label label-primary\">项目负责人</span>&nbsp;<span class=\"main-partner\">");
      if (_jspx_meth_s_005fproperty_005f2(_jspx_page_context))
        return;
      out.write("</span</p>\r\n");
      out.write("          <p><span class=\"label label-primary\">项目成员</span>&nbsp;<span class=\"other-partner\">");
      if (_jspx_meth_s_005fproperty_005f3(_jspx_page_context))
        return;
      out.write("</span></p>\r\n");
      out.write("          <p><span class=\"label label-primary\">项目类别</span>&nbsp;<span class=\"other-partner\">");
      if (_jspx_meth_s_005fproperty_005f4(_jspx_page_context))
        return;
      out.write("</span></p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <p class=\"project-introduction\">\r\n");
      out.write("            <span class=\"label label-primary\">项目简介</span>\r\n");
      out.write("            <p class=\"project-introduction\">");
      if (_jspx_meth_s_005fproperty_005f5(_jspx_page_context))
        return;
      out.write("</p>\r\n");
      out.write("        </p>\r\n");
      out.write("        <div class=\"vote-box\" data-toggle=\"modal\" data-target=\"#vote-modal\">\r\n");
      out.write("          <span class=\"glyphicon glyphicon-heart-empty vote-heart\" aria-hidden=\"true\"></span>\r\n");
      out.write("          <span class=\"vote\">投票</span>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!--vote-modal-->\r\n");
      out.write("  <div class=\"modal fade\" id=\"vote-modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <div class=\"modal-header\">\r\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">\r\n");
      out.write("            &times;\r\n");
      out.write("          </button>\r\n");
      out.write("            <h4 class=\"modal-title\" id=\"myModalLabel\">\r\n");
      out.write("              投票\r\n");
      out.write("           </h4>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-body\" style=\"overflow: hidden\">\r\n");
      out.write("          <div class=\"col-lg-12\">\r\n");
      out.write("            <form id=\"form\" class=\"form-horizontal\" role=\"form\">\r\n");
      out.write("              <div class=\"input-group\" style=\"opacity: 0\">\r\n");
      out.write("                  <input type=\"text\" class=\"form-control\" value=\"");
      if (_jspx_meth_s_005fproperty_005f6(_jspx_page_context))
        return;
      out.write("\" name=\"ProjectID\" readonly=\"readonly\"  id=\"ProjectID\"/>                                       \r\n");
      out.write("              </div>\r\n");
      out.write("              <div id=\"vote-user\" class=\"form-group\">\r\n");
      out.write("                <label class=\"col-sm-2 control-label\">学号</label>\r\n");
      out.write("                <div class=\"col-sm-10\">\r\n");
      out.write("                  <input class=\"textin form-control\" type=\"text\" placeholder=\"学号\"  aria-describedby=\"sno-attention\"  name=\"userNo\">\r\n");
      out.write("                  <span id=\"sno-attention\" class=\"help-block\">注意只能刷卡后才能进行投票</span>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div id=\"vote-psw\" class=\"form-group\">\r\n");
      out.write("                <label class=\"col-sm-2 control-label\">密码</label>\r\n");
      out.write("                <div class=\"col-sm-10\">\r\n");
      out.write("                  <input class=\"textin form-control\" type=\"text\" placeholder=\"密码\" aria-describedby=\"psw-attention\"  name=\"password\">\r\n");
      out.write("                  <span id=\"psw-attention\" class=\"help-block\">密码为学号后六位</span>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-sm-12 alert alert-danger\" role=\"alert\" id=\"vote-attention\">\r\n");
      out.write("                   输入不允许为空\r\n");
      out.write("              </div>\r\n");
      out.write("            </form>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-footer\">\r\n");
      out.write("          <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">关闭\r\n");
      out.write("          </button>\r\n");
      out.write("          <button  type=\"button\" class=\"btn btn-primary\" data-toggle=\"modal\" id=\"vote-button\">\r\n");
      out.write("            投票\r\n");
      out.write("          </button>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!--lottery-modal-->\r\n");
      out.write("  <div class=\"modal fade\" id=\"lottery-modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <div class=\"modal-header\">\r\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">\r\n");
      out.write("            &times;\r\n");
      out.write("          </button>\r\n");
      out.write("          <h4 class=\"modal-title\" id=\"myModalLabel\">\r\n");
      out.write("            抽奖\r\n");
      out.write("         </h4>\r\n");
      out.write("        </div>\r\n");
      out.write("          <div class=\"modal-body\" style=\"overflow: hidden\">\r\n");
      out.write("            <div class=\"col-lg-12\">\r\n");
      out.write("              <form id=\"form\" class=\"form-horizontal\" role=\"form\">\r\n");
      out.write("                <div id=\"lottery-user\" class=\"form-group\">\r\n");
      out.write("                  <label class=\"col-sm-2 control-label\">用户名</label>\r\n");
      out.write("                  <div class=\"col-sm-10\">\r\n");
      out.write("                    <input class=\"textin form-control\" type=\"text\" placeholder=\"用户名\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"lottery-psw\" class=\"form-group\">\r\n");
      out.write("                  <label class=\"col-sm-2 control-label\">密码</label>\r\n");
      out.write("                  <div class=\"col-sm-10\">\r\n");
      out.write("                    <input class=\"textin form-control\" type=\"text\" placeholder=\"密码为学号后六位\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!--<div id=\"lottery-check\" class=\"form-group\">\r\n");
      out.write("                  <label class=\"col-sm-2 control-label\">验证码</label>\r\n");
      out.write("                  <div class=\"col-sm-8\">\r\n");
      out.write("                    <input class=\"textin form-control\" type=\"text\" placeholder=\"验证码\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"col-sm-2\"><img src=\"\" style=\"width: 100%\"></div>\r\n");
      out.write("                </div>-->\r\n");
      out.write("              </form>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        <div class=\"modal-footer\">\r\n");
      out.write("          <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">关闭\r\n");
      out.write("          </button>\r\n");
      out.write("          <button type=\"button\" class=\"btn btn-primary\" data-toggle=\"modal\" data-target=\"#lottery-result\">\r\n");
      out.write("            抽奖\r\n");
      out.write("          </button>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!--lottery-result-->\r\n");
      out.write("  <div class=\"modal fade\" id=\"lottery-result\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\" data-backdrop=\"static\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <div class=\"modal-header\">\r\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">\r\n");
      out.write("            &times;\r\n");
      out.write("          </button>\r\n");
      out.write("          <h4 class=\"modal-title\" id=\"myModalLabel\">\r\n");
      out.write("            抽奖结果\r\n");
      out.write("         </h4>\r\n");
      out.write("        </div>\r\n");
      out.write("          <div class=\"modal-body\" style=\"overflow: hidden\">\r\n");
      out.write("            <div class=\"col-lg-12 success\">\r\n");
      out.write("                <div>\r\n");
      out.write("                  恭喜你抽中<span id=\"lo-result\"></span>等奖!\r\n");
      out.write("                </div>\r\n");
      out.write("                <label class=\"col-sm-4 address-lab\">请填写你的姓名：</label>\r\n");
      out.write("                <div class=\"col-sm-8 name\">\r\n");
      out.write("                    <input class=\"textin form-control\" type=\"text\" placeholder=\"你的姓名\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <label class=\"col-sm-4 address-lab\">请填写收货地址：</label>\r\n");
      out.write("                <div class=\"col-sm-8 address\">\r\n");
      out.write("                    <input class=\"textin form-control\" type=\"text\" placeholder=\"收货地址\">\r\n");
      out.write("                </div>\r\n");
      out.write("               \r\n");
      out.write("                <label class=\"col-sm-4 address-lab\">请填写你的电话：</label>\r\n");
      out.write("                <div class=\"col-sm-8 phone\">\r\n");
      out.write("                    <input class=\"textin form-control\" type=\"text\" placeholder=\"你的电话\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div style=\"color: red;\">\r\n");
      out.write("                  请认真填写，只有这一次机会！\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"fail\">\r\n");
      out.write("              很遗憾你没抽中，再接再厉~\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"enough\">\r\n");
      out.write("              很遗憾你的抽奖次数已达上限10次，不能再抽奖啦！\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"hassucceed\">\r\n");
      out.write("            \t你已经中过奖啦！不能再抽了！ \r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"logerror\">\r\n");
      out.write("            \t抱歉登录异常！请检查用户名和密码是否正确！\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        <div class=\"modal-footer\">\r\n");
      out.write("          <button type=\"button\" class=\"btn btn-default closeUp\" data-dismiss=\"modal\">关闭\r\n");
      out.write("          </button>\r\n");
      out.write("          <button type=\"button\" class=\"btn btn-default lotteryUp\">提交\r\n");
      out.write("          </button>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <script src=\"js/projectDetail.js\"></script>\r\n");
      out.write("  <script src=\"js/index.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("  \t$(function(){\r\n");
      out.write("  \t\t\t/*var length = $(\".project-detail-img-box\").find(\"img\").length;\r\n");
      out.write("\t\t\t\tfor(var i = 0;i<length;i++){\r\n");
      out.write("\t\t\t\t   var re = \"file:///C:/vote/InnovationVote/\";\r\n");
      out.write("\t\t\t\t   var src = $(\".project-detail-img-box\").find(\"img\")[i].src;\r\n");
      out.write("\t\t\t\t   $(\".project-detail-img-box\").find(\"img\")[i].src = src.replace(re,\"\")\r\n");
      out.write("\t\t\t\t}*/\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t  var src = $(\".detail-img-src\").text();\r\n");
      out.write("\t\t\t\tvar re = \"C:\\\\vote\\\\InnovationVote\\\\\";\r\n");
      out.write("\t\t\t\tsrc = src.replace(re,\"\");\r\n");
      out.write("\t\t\t\t$(\".project-detail-img-box\").find(\"img\")[0].src = src;\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\tvar rr = /picture/;\r\n");
      out.write("\t\t\t  var src = $(\".project-detail-img-box\").find(\"img\")[0].src;\r\n");
      out.write("\t\t\t  if(!rr.test(src))\r\n");
      out.write("\t\t\t\t  $(\".project-detail-img-box\").find(\"img\")[0].src = \"/images/logo.png\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("  \t)\r\n");
      out.write("  \t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_s_005fproperty_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f0 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f0.setParent(null);
    // /project.jsp(73,58) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f0.setValue("#request.project.ProjectImage");
    int _jspx_eval_s_005fproperty_005f0 = _jspx_th_s_005fproperty_005f0.doStartTag();
    if (_jspx_th_s_005fproperty_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f1 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f1.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f1.setParent(null);
    // /project.jsp(77,34) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f1.setValue("#request.project.projectName");
    int _jspx_eval_s_005fproperty_005f1 = _jspx_th_s_005fproperty_005f1.doStartTag();
    if (_jspx_th_s_005fproperty_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f1);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f2 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f2.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f2.setParent(null);
    // /project.jsp(79,92) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f2.setValue("#request.project.LeaderName");
    int _jspx_eval_s_005fproperty_005f2 = _jspx_th_s_005fproperty_005f2.doStartTag();
    if (_jspx_th_s_005fproperty_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f2);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f3 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f3.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f3.setParent(null);
    // /project.jsp(80,92) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f3.setValue("#request.project.ProjectMembers");
    int _jspx_eval_s_005fproperty_005f3 = _jspx_th_s_005fproperty_005f3.doStartTag();
    if (_jspx_th_s_005fproperty_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f3);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f4 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f4.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f4.setParent(null);
    // /project.jsp(81,92) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f4.setValue("#request.project.ProjectType");
    int _jspx_eval_s_005fproperty_005f4 = _jspx_th_s_005fproperty_005f4.doStartTag();
    if (_jspx_th_s_005fproperty_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f4);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f5 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f5.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f5.setParent(null);
    // /project.jsp(85,44) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f5.setValue("#request.project.ProjectIntroduction");
    int _jspx_eval_s_005fproperty_005f5 = _jspx_th_s_005fproperty_005f5.doStartTag();
    if (_jspx_th_s_005fproperty_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f5);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f6 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f6.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f6.setParent(null);
    // /project.jsp(110,65) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f6.setValue("#request.project.ProjectID");
    int _jspx_eval_s_005fproperty_005f6 = _jspx_th_s_005fproperty_005f6.doStartTag();
    if (_jspx_th_s_005fproperty_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f6);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f6);
    return false;
  }
}
