/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2016-05-17 04:04:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class projectSubmit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<!-- \r\n");
      out.write(" -->\r\n");
      out.write("<head>\r\n");
      out.write("  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <meta name=\"description\" content=\"\">\r\n");
      out.write("  <meta name=\"author\" content=\"\">\r\n");
      out.write("  <title>大创展项目提交系统</title>\r\n");
      out.write("  <!-- Bootstrap -->\r\n");
      out.write("  <link href=\"css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"css/bootstrap-theme.css\" rel=\"stylesheet\">\r\n");
      out.write("  <!-- simple style -->\r\n");
      out.write("  <link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/projectSubmit.css\">\r\n");
      out.write("  <style type=\"text/css\">\r\n");
      out.write("  body {\r\n");
      out.write("    background-color: #f6f6f6;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  #logo-text,\r\n");
      out.write("  #login {\r\n");
      out.write("    color: #ffffff;\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  #logo {\r\n");
      out.write("    padding-top: 5px;\r\n");
      out.write("  }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t");
  
  Object username = session.getAttribute("project_id");  
  if(null == username){  
        
      response.sendRedirect("login.jsp");  
  }  

      out.write("\r\n");
      out.write("  <!-- Fixed navbar -->\r\n");
      out.write("    <nav class=\"navbar navbar-inverse navbar-fixed-top\" role=\"navigation\">\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("      <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#example-navbar-collapse\">\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("      </button>\r\n");
      out.write("      <a class=\"navbar-brand\" id=\"logo\" href=\"index.jsp\" style=\"margin-bottom: 5px\"><img src=\"images/logo.png\" weight=\"45px\" height=\"45px\" /></a>\r\n");
      out.write("    </div>\r\n");
      out.write("         <ul class=\"nav navbar-nav navbar-right\" style=\"margin-right: 20px\">\r\n");
      out.write("        <div class=\"dropdown pull-right\">\r\n");
      out.write("          <button class=\"btn dropdown-toggle\" type=\"button\" id=\"login-name\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"true\">\r\n");
      out.write("            ");
      if (_jspx_meth_s_005fproperty_005f0(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("            <span class=\"caret\"></span>\r\n");
      out.write("          </button>\r\n");
      out.write("          <ul class=\"dropdown-menu\" aria-labelledby=\"dropdownMenu1\">\r\n");
      out.write("            <li><a href=\"changePassword.jsp\">修改密码</a></li>\r\n");
      out.write("            <li><a href=\"logout.action\">注销</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>\r\n");
      out.write("  <!--project-submit-->\r\n");
      out.write("  <div id=\"submit-main\" class=\"container\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("      <div id=\"submit-box\" class=\"col-md-12\" >\r\n");
      out.write("        <div class=\"col-md-6 col-xs-12 submit-box-left-info\">\r\n");
      out.write("          <h1 class=\"text-center\">Don't</h1>\r\n");
      out.write("          <h2 class=\"text-center\">lose your idea！</h2>\r\n");
      out.write("          <img src=\"./images/WIN-1.png\" alt=\"\" class=\"img-responsive\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-6\">\r\n");
      out.write("          <form id=\"submit-form\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("            <!--submit-project-id-->\r\n");
      out.write("            <!--<div class=\"form-group\">\r\n");
      out.write("              <label for=\"submit-project-id\">项目ID</label>\r\n");
      out.write("              <input type=\"text\" id=\"submit-project-id\" class=\"form-control\" name=\"project_id\" required>\r\n");
      out.write("            </div>-->\r\n");
      out.write("            <!--submit-project-title-->\r\n");
      out.write("            <!--<div class=\"form-group\">\r\n");
      out.write("              <label for=\"submit-project-title\">项目标题</label>\r\n");
      out.write("              <input type=\"text\" id=\"submit-project-title\" class=\"form-control\" name=\"project_title\" aria-describedby=\"submit-project-title-help\" required>\r\n");
      out.write("              <span id=\"submit-project-title-help\" class=\"help-block\">不要提交过长的项目标题,否则有可能会影响显示体验</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--submit-type-->\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("              <label for=\"submit-type\">项目类别</label>\r\n");
      out.write("              <select id=\"submit-type\" class=\"form-control\" name=\"project_type\">\r\n");
      out.write("                <option value=\"智能硬件\"智能硬件</option>\r\n");
      out.write("                <option value=\"互联网+\">互联网+</option>\r\n");
      out.write("                <option value=\"智慧生活\">智慧生活</option>\r\n");
      out.write("                <option value=\"电子\">电子</option>\r\n");
      out.write("                <option value=\"数理\">数理</option>\r\n");
      out.write("                <option value=\"软件\">软件</option>\r\n");
      out.write("                <option value=\"创意\">创意</option>\r\n");
      out.write("                <option value=\"论文\">论文</option>\r\n");
      out.write("                <option value=\"通信\">通信</option>\r\n");
      out.write("                <option value=\"模式识别与机器学习\">模式识别与机器学习</option>\r\n");
      out.write("                <!--<option value=\"其他\">其他</option>-->\r\n");
      out.write("              </select>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--submit-main-partner-->\r\n");
      out.write("            <!--<div class=\"form-group\">\r\n");
      out.write("               <label for=\"submit-main-partner\">项目主要负责人</label>\r\n");
      out.write("              <input type=\"text\" id=\"submit-main-partner\" class=\"form-control\" name=\"main_partner\" aria-describedby=\"submit-main-partner-help\" required>\r\n");
      out.write("              <span id=\"submit-other-partner-help\" class=\"help-block\">输入样例：马小云</span>\r\n");
      out.write("            </div>-->\r\n");
      out.write("            <!--submit-other-partner-->\r\n");
      out.write("            <!--<div class=\"form-group\">\r\n");
      out.write("              <label for=\"submit-other-partner\">项目其他成员</label>\r\n");
      out.write("              <input type=\"text\" id=\"submit-other-partner\" class=\"form-control\"  name=\"other_partner\" aria-describedby=\"submit-other-partner-help\" required>\r\n");
      out.write("               <span id=\"submit-other-partner-help\" class=\"help-block\">输入样例：小明，小红，小张</span>\r\n");
      out.write("            </div>-->\r\n");
      out.write("            \r\n");
      out.write("            <!--submit-img-->\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("              <label for=\"submit-img\">上传照片</label>\r\n");
      out.write("              <input type=\"file\" id=\"submit-img\" name=\"project_img\">\r\n");
      out.write("              <p class=\"help-block\">不要上传过大的照片，上传jpg/jpeg/png格式照片</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--submit-project-introduction-->\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("              <label for=\"submit-project-introduction\">项目简介</label>\r\n");
      out.write("              <textarea id=\"submit-project-introduction\" class=\"form-control\" name=\"project_introduction\" rows=\"5\" required maxlength=\"200\" aria-describedby=\"submit-project-introduction-help\" style=\"resize: none;\"></textarea>\r\n");
      out.write("              <span id=\"submit-project-introduction-help\" class=\"help-block\">填写项目介绍，150~200字</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--CAPTCHA-->\r\n");
      out.write("            <!--<div class=\"form-group\">\r\n");
      out.write("              <label for=\"submit-CAPTCHA\">验证码</label>\r\n");
      out.write("              <input id=\"submit-CAPTCHA\" type=\"text\" name=\"CAPTHA\" placeholder=\"验证码\">\r\n");
      out.write("              <img src=\"images/2.jpg\">\r\n");
      out.write("              <span class=\"submit-CAPTCHA-text\"></span>\r\n");
      out.write("            </div>-->\r\n");
      out.write("            <!--submit-info-->\r\n");
      out.write("            <div class=\"submit-info\">\r\n");
      out.write("              <p>你现在可以修改/提交当页内容,请使用chrome7+，IE10+，Safari5+或其他浏览器高速模式提交，否则会导致提交失败，请注意</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--submit-->\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-primary btn-submit pull-right\" id=\"submit-project\">提交</button>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!--lottery-modal-->\r\n");
      out.write("  <div class=\"modal fade\" id=\"lottery-modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <div class=\"modal-header\">\r\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">\r\n");
      out.write("            &times;\r\n");
      out.write("          </button>\r\n");
      out.write("          <h4 class=\"modal-title\" id=\"myModalLabel\">\r\n");
      out.write("            抽奖\r\n");
      out.write("         </h4>\r\n");
      out.write("        </div>\r\n");
      out.write("          <div class=\"modal-body\" style=\"overflow: hidden\">\r\n");
      out.write("            <div class=\"col-lg-12\">\r\n");
      out.write("              <form id=\"project-submit-form\" class=\"form-horizontal\" role=\"form\">\r\n");
      out.write("                <div id=\"lottery-user\" class=\"form-group\">\r\n");
      out.write("                  <label class=\"col-sm-2 control-label\">用户名</label>\r\n");
      out.write("                  <div class=\"col-sm-10\">\r\n");
      out.write("                    <input class=\"textin form-control\" type=\"text\" placeholder=\"用户名\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"lottery-psw\" class=\"form-group\">\r\n");
      out.write("                  <label class=\"col-sm-2 control-label\">密码</label>\r\n");
      out.write("                  <div class=\"col-sm-10\">\r\n");
      out.write("                    <input class=\"textin form-control\" type=\"text\" placeholder=\"密码\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("               <div id=\"lottery-check\" class=\"form-group\">\r\n");
      out.write("                  <label class=\"col-sm-2 control-label\">验证码</label>\r\n");
      out.write("                  <div class=\"col-sm-8\">\r\n");
      out.write("                    <input class=\"textin form-control\" type=\"text\" placeholder=\"验证码\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"col-sm-2\"><img src=\"\" style=\"width: 100%\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </form>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        <div class=\"modal-footer\">\r\n");
      out.write("          <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">关闭\r\n");
      out.write("          </button>\r\n");
      out.write("          <button type=\"button\" class=\"btn btn-primary\" data-toggle=\"modal\" data-target=\"#lottery-result\">\r\n");
      out.write("            抽奖\r\n");
      out.write("          </button>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write(" <!--submit-result-->\r\n");
      out.write("<div class=\"modal fade\" id=\"submit-result\">\r\n");
      out.write("  <div class=\"modal-dialog\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>\r\n");
      out.write("        <h4 class=\"modal-title\">提交结果</h4>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body modal-text\">\r\n");
      out.write("        <p>不允许有空值</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">关闭</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div><!-- /.modal-content -->\r\n");
      out.write("  </div><!-- /.modal-dialog -->\r\n");
      out.write("</div><!-- /.modal -->\r\n");
      out.write("\r\n");
      out.write("  <!--lottery-result-->\r\n");
      out.write("  <div class=\"modal fade\" id=\"lottery-result\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <div class=\"modal-header\">\r\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">\r\n");
      out.write("            &times;\r\n");
      out.write("          </button>\r\n");
      out.write("          <h4 class=\"modal-title\" id=\"myModalLabel\">\r\n");
      out.write("            抽奖结果\r\n");
      out.write("         </h4>\r\n");
      out.write("        </div>\r\n");
      out.write("          <div class=\"modal-body\" style=\"overflow: hidden\">\r\n");
      out.write("            <div class=\"success\">\r\n");
      out.write("              恭喜你抽中<span id=\"lo-result\"></span>等奖!\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"fail\">\r\n");
      out.write("              很遗憾你没抽中，再接再厉~\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        <div class=\"modal-footer\">\r\n");
      out.write("          <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">关闭\r\n");
      out.write("          </button>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <script src=\"http://apps.bdimg.com/libs/jquery/1.11.3/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("  <script src=\"js/projectSubmit.js\"></script>\r\n");
      out.write("  <script src=\"js/index.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_s_005fproperty_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f0 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f0.setParent(null);
    // /projectSubmit.jsp(56,12) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f0.setValue("username");
    int _jspx_eval_s_005fproperty_005f0 = _jspx_th_s_005fproperty_005f0.doStartTag();
    if (_jspx_th_s_005fproperty_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f0);
    return false;
  }
}
