/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2016-05-02 02:47:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Upload_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005ffielderror_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fs_005ffielderror_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fs_005ffielderror_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=GBK");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html l\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<title>上传图片 </title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("<Center>\r\n");
      out.write("\t  <FONT color=\"red\">\r\n");
      out.write("                 ");
      if (_jspx_meth_s_005ffielderror_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                  </FONT>\r\n");
      out.write("\t\r\n");
      out.write(" 请选择需要上传的图片 <br>\r\n");
      out.write("<form action=\"upload\" method=\"post\" enctype=\"multipart/form-data\" >\r\n");
      out.write("\t            <label for=\"submit-project-id\">项目ID</label>\r\n");
      out.write("              <input type=\"text\" id=\"submit-project-id\" class=\"form-control\" name=\"project_id\" required>\r\n");
      out.write("              \r\n");
      out.write("              <label for=\"submit-project-title\">项目标题</label>\r\n");
      out.write("              <input type=\"text\" id=\"submit-project-title\" class=\"form-control\" name=\"project_title\" aria-describedby=\"submit-project-title-help\" required>\r\n");
      out.write("              <span id=\"submit-project-title-help\" class=\"help-block\">不要提交过长的项目标题,否则有可能会影响显示体验</span>\r\n");
      out.write("              \r\n");
      out.write("              <label for=\"submit-type\">项目类别</label>\r\n");
      out.write("              <select id=\"submit-type\" class=\"form-control\" name=\"project_type\">\r\n");
      out.write("                <option value=\"智能硬件\"智能硬件</option>\r\n");
      out.write("                <option value=\"互联网+\">互联网+</option>\r\n");
      out.write("                <option value=\"智慧生活\">智慧生活</option>\r\n");
      out.write("                <option value=\"电子\">电子</option>\r\n");
      out.write("                <option value=\"数理\">数理</option>\r\n");
      out.write("                <option value=\"软件\">软件</option>\r\n");
      out.write("                <option value=\"创意\">创意</option>\r\n");
      out.write("                <option value=\"论文\">论文</option>\r\n");
      out.write("                <option value=\"通信\">通信</option>\r\n");
      out.write("                <option value=\"模式识别与机器学习\">模式识别与机器学习</option>\r\n");
      out.write("                <option value=\"其他\">其他</option>\r\n");
      out.write("              </select>\r\n");
      out.write("              \r\n");
      out.write("               <label for=\"submit-main-partner\">项目主要负责人</label>\r\n");
      out.write("              <input type=\"text\" id=\"submit-main-partner\" class=\"form-control\" name=\"main_partner\" aria-describedby=\"submit-main-partner-help\" required>\r\n");
      out.write("              <span id=\"submit-other-partner-help\" class=\"help-block\">输入样例：马小云</span>\r\n");
      out.write("           \r\n");
      out.write("            <!--submit-other-partner-->\r\n");
      out.write("           \r\n");
      out.write("              <label for=\"submit-other-partner\">项目其他成员</label>\r\n");
      out.write("              <input type=\"text\" id=\"submit-other-partner\" class=\"form-control\"  name=\"other_partner\" aria-describedby=\"submit-other-partner-help\" required>\r\n");
      out.write("               <span id=\"submit-other-partner-help\" class=\"help-block\">输入样例：小明，小红，小张</span>\r\n");
      out.write("          \r\n");
      out.write("            <!--submit-img-->\r\n");
      out.write("           \r\n");
      out.write("              <label for=\"submit-img\">上传照片</label>\r\n");
      out.write("              <input type=\"file\" id=\"submit-img\" name=\"project_img\">\r\n");
      out.write("              <p class=\"help-block\">不要上传过大的照片，上传jpg/jpeg/png格式照片</p>\r\n");
      out.write("           \r\n");
      out.write("          \r\n");
      out.write("              <label for=\"submit-project-introduction\">项目简介</label>\r\n");
      out.write("              <textarea id=\"submit-project-introduction\" class=\"form-control\" name=\"project_introduction\" rows=\"5\" required maxlength=\"200\" aria-describedby=\"submit-project-introduction-help\" style=\"resize: none;\"></textarea>\r\n");
      out.write("              <span id=\"submit-project-introduction-help\" class=\"help-block\">填写项目介绍，150~200字 </span>\r\n");
      out.write("              <input type=\"submit\" name=\"Submit\">\r\n");
      out.write("         \r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_s_005ffielderror_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:fielderror
    org.apache.struts2.views.jsp.ui.FieldErrorTag _jspx_th_s_005ffielderror_005f0 = (org.apache.struts2.views.jsp.ui.FieldErrorTag) _005fjspx_005ftagPool_005fs_005ffielderror_005fnobody.get(org.apache.struts2.views.jsp.ui.FieldErrorTag.class);
    _jspx_th_s_005ffielderror_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005ffielderror_005f0.setParent(null);
    int _jspx_eval_s_005ffielderror_005f0 = _jspx_th_s_005ffielderror_005f0.doStartTag();
    if (_jspx_th_s_005ffielderror_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005ffielderror_005fnobody.reuse(_jspx_th_s_005ffielderror_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005ffielderror_005fnobody.reuse(_jspx_th_s_005ffielderror_005f0);
    return false;
  }
}
