/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-05-18 10:14:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import db.fun.*;
import db.pojo.*;
import struts.UserVote.*;

public final class user_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005ffielderror_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fs_005ffielderror_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fs_005ffielderror_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("OCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("    <title>大创展投票系统</title>\r\n");
      out.write("    <!-- Bootstrap -->\r\n");
      out.write("    <link href=\"css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/bootstrap-theme.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- siimple style -->\r\n");
      out.write("    <link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/templatemo_style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("        * {\r\n");
      out.write("            font-family: \"Microsoft YaHei\"\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        body {\r\n");
      out.write("            background-color: #f6f6f6;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .pro-image {\r\n");
      out.write("            width: 20px;\r\n");
      out.write("            height: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #logo-text,\r\n");
      out.write("        #login {\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #logo {\r\n");
      out.write("            padding-top: 5px;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Fixed navbar -->\r\n");
      out.write("    <div class=\"navbar navbar-inverse navbar-fixed-top\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"navbar-header\">\r\n");
      out.write("                <!--           <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("          </button> -->\r\n");
      out.write("                <a class=\"navbar-brand\" id=\"logo\" href=\"index.jsp\"><img src=\"images/logo.png\" weight=\"48px\" height=\"48px\" /></a>\r\n");
      out.write("                <p class=\"navbar-text\" id=\"logo-text\">InnovationCamp</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"navbar-collapse collapse\">\r\n");
      out.write("                <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("                    <li><a href=\"loginAdmin.jsp\" id=\"login\">login in</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
 if(session.getAttribute( "username") == null ){ 
      out.write("\r\n");
      out.write("    <div class=\"col-lg-4 col-lg-offset-4\">\r\n");
      out.write("    \t<h1>管理员未登录</h1>\r\n");
      out.write("    \t<a href=\"loginAdmin.jsp\" >重新登录</a>\r\n");
      out.write("      ");
 }   else{String Username=session.getAttribute("username").toString();String 	UserNo=session.getAttribute("UserNo").toString();
      	out.print(Username);out.print(UserNo);
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"header\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-8\">\r\n");
      out.write("                    <div class=\"panel panel-primary\">\r\n");
      out.write("                        <div class=\"panel-heading\">\r\n");
      out.write("                            项目名称<span class=\"label\"></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"panel-body\">\r\n");
      out.write("                        \t\t<form action=\"DeleteVote\"  method=\"post\" >\r\n");
      out.write("                        \t\t\t\t<input type=\"hidden\" name=\"UserNo\" value=\"");
      out.print(UserNo );
      out.write("\" />用户名：  ");
      out.print(UserNo );
      out.write("  \r\n");
      out.write("                            \t\t<table class=\"table table-hover\">\r\n");
      out.write("                            \t\t\t\t<tr>\r\n");
      out.write("                            \t\t\t\t\t\t<th></th>\r\n");
      out.write("                                        <th>项目编号</th>\r\n");
      out.write("                                        <th>项目名称</th>\r\n");
      out.write("                                        <th>当前票数</th>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    ");
 List list=new FunUserData().userVote(UserNo);	
                                    	 VoteRecord[] v = new VoteRecord[list.size()]; 	
                                    	 Long[] l = new Long[list.size()];
                                    	 ProjectInfo[] p = new ProjectInfo[list.size()];
      out.write("\r\n");
      out.write("                                    ");
 for(int i=0; i<list.size();i++) { 
      out.write("\r\n");
      out.write("                                   \t\t\t<tr>\r\n");
      out.write("                                        \t\t<td>\r\n");
      out.write("                                        \t\t\t\t<img class=\"img-circle pro_image\" src=\"images/user_face.jpg\" width=\"35px\" height=\"35px\" />\r\n");
      out.write("                                        \t\t</td>\r\n");
      out.write("                                            <td>\r\n");
      out.write("                                                ");
 v[i] = (VoteRecord)list.get(i); l[i] = v[i].getProjectID();
      out.write(' ');
      out.write(' ');
      out.print( l[i] );
      out.write("\r\n");
      out.write("                                            </td>\r\n");
      out.write("                                            <td>\r\n");
      out.write("                                                <a href=\"project.action?projectID=");
      out.print(l[i] );
      out.write("\">\r\n");
      out.write("                                                ");
 p[i] = new FunProjectInfo().projectInfo(l[i]); 
      out.write("\r\n");
      out.write("                                                ");
      out.print( p[i].getProjectName());
      out.write("\r\n");
      out.write("                                                \r\n");
      out.write("                                                </a>\r\n");
      out.write("                                                \r\n");
      out.write("                                            </td>\r\n");
      out.write("                                            <td>\r\n");
      out.write("                                                ");
      out.print( p[i].getVoteNum() );
      out.write("\r\n");
      out.write("                                                <input type=\"radio\" name=\"ProjectID\" value=\"");
      out.print(((VoteRecord)list.get(i)).getProjectID() );
      out.write("\" check=\"checked\" />\r\n");
      out.write("                                            </td>\r\n");
      out.write("                                               \r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                    ");
 } 
      out.write("\r\n");
      out.write("                                </table>\r\n");
      out.write("                                </br>\r\n");
      out.write("                                </br>\r\n");
      out.write("                                \r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                    <div class=\"col-lg-10\">\r\n");
      out.write("                        <div class=\"control-wrapper col-md-offset-1\">\r\n");
      out.write("                            ");
      if (_jspx_meth_s_005ffielderror_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                                </br>\r\n");
      out.write("                                </br>\r\n");
      out.write("                                 <td class=\"text-center\">\r\n");
      out.write("                                               <input  class=\"btn btn-primary btn-block\" type=\"submit\" value=\"确认删除\" />\r\n");
      out.write("                                                </td>\r\n");
      out.write("                          </form>\r\n");
      out.write("                \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4\">\r\n");
      out.write("                    <div class=\"panel panel-primary\">\r\n");
      out.write("                        <div class=\"panel-heading text-center\">大创展投票系统</div>\r\n");
      out.write("                        <div class=\"panel-body\">\r\n");
      out.write("                            <div class=\"row\"><img id=\"pro_logo\" src=\"images/user_face.jpg\" class=\"center-block img-circle\" alt=\"Image\"></div>\r\n");
      out.write("                            <br/>\r\n");
      out.write("                            <div class=\"text-center\">\r\n");
      out.write("                                <p>\r\n");
      out.write("                                    <h4>用户名：");
      out.print(new FunUserData().userInfo(UserNo).getName() );
      out.write("</h4></p>\r\n");
      out.write("                                <p>\r\n");
      out.write("                                    <h4>学号：");
      out.print(new FunUserData().userInfo(UserNo).getOutID() );
      out.write("</h4></p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <br/>\r\n");
      out.write("                            <form class=\"form-inline signup\" role=\"form\" action=\"projectSearch\" method=\"get\">\r\n");
      out.write("                                <div class=\"input-group\">\r\n");
      out.write("                                \t  <input type=\"text\" class=\"form-control\" placeholder=\"搜索项目\" name=\"search\">\r\n");
      out.write("                                    <span class=\"input-group-btn\">\r\n");
      out.write("                                <button type=\"submit\" class=\"btn btn-info\">走你</button>\r\n");
      out.write("                            </span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </form>\r\n");
      out.write("                            <form action=\"Loginout\" method=\"post\">\r\n");
      out.write("                            \t\t<input type=\"hidden\" name=\"username\" value=\"");
      out.print(Username );
      out.write("\" />\r\n");
      out.write("                            \t\t<input type=\"hidden\" name=\"UserNo\" value=\"");
      out.print(UserNo );
      out.write("\" />\r\n");
      out.write("                                <input  class=\"btn btn-primary btn-block\" type=\"submit\" value=\"退出\" />\r\n");
      out.write("                          \t</form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
 }  
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_s_005ffielderror_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:fielderror
    org.apache.struts2.views.jsp.ui.FieldErrorTag _jspx_th_s_005ffielderror_005f0 = (org.apache.struts2.views.jsp.ui.FieldErrorTag) _005fjspx_005ftagPool_005fs_005ffielderror_005fnobody.get(org.apache.struts2.views.jsp.ui.FieldErrorTag.class);
    _jspx_th_s_005ffielderror_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005ffielderror_005f0.setParent(null);
    int _jspx_eval_s_005ffielderror_005f0 = _jspx_th_s_005ffielderror_005f0.doStartTag();
    if (_jspx_th_s_005ffielderror_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005ffielderror_005fnobody.reuse(_jspx_th_s_005ffielderror_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005ffielderror_005fnobody.reuse(_jspx_th_s_005ffielderror_005f0);
    return false;
  }
}
