/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2016-05-17 05:40:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class voteresult_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("  <meta name=\"description\" content=\"\">\n");
      out.write("  <meta name=\"author\" content=\"\">\n");
      out.write("  <title>大创展投票系统</title>\n");
      out.write("  <!-- Bootstrap -->\n");
      out.write("  <link href=\"css/bootstrap.css\" rel=\"stylesheet\">\n");
      out.write("  <link href=\"css/bootstrap-theme.css\" rel=\"stylesheet\">\n");
      out.write("  <link href=\"css/vegas.min.css\" rel=\"stylesheet\">\n");
      out.write("  <!-- simple style -->\n");
      out.write("  <link href=\"css/style.css\" rel=\"stylesheet\">\n");
      out.write("  <style type=\"text/css\">\n");
      out.write("  body {\n");
      out.write("    background-color: #f6f6f6;\n");
      out.write("  }\n");
      out.write("  \n");
      out.write("  #logo-text {\n");
      out.write("    color: #ffffff;\n");
      out.write("    font-size: 20px;\n");
      out.write("  }\n");
      out.write("  \n");
      out.write("  #logo {\n");
      out.write("    padding-top: 5px;\n");
      out.write("  }\n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("  <!-- Fixed navbar -->\n");
      out.write("  <nav class=\"navbar navbar-inverse navbar-fixed-top\" role=\"navigation\">\n");
      out.write("    <div class=\"navbar-header\">\n");
      out.write("      <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#example-navbar-collapse\">\n");
      out.write("        <span class=\"icon-bar\"></span>\n");
      out.write("        <span class=\"icon-bar\"></span>\n");
      out.write("        <span class=\"icon-bar\"></span>\n");
      out.write("      </button>\n");
      out.write("      <a class=\"navbar-brand\" id=\"logo\" href=\"index.jsp\" style=\"margin-bottom: 5px\"><img src=\"images/logo.png\" weight=\"45px\" height=\"45px\" /></a>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"example-navbar-collapse\">\n");
      out.write("      <ul class=\"nav navbar-nav\">\n");
      out.write("        <li><a href=\"projectSearch.action?Judge=0\">我要投票</a></li>\n");
      out.write("        <!--<li><a href=\"#\" data-toggle=\"modal\" data-target=\"#lottery-modal\">我要抽奖</a></li>-->\n");
      out.write("        <!--<li><a href=\"#\">项目列表</a></li>-->\n");
      out.write("      </ul>\n");
      out.write("     <!-- <form class=\"navbar-form navbar-left\" role=\"search\" action=\"project\" method=\"POST\">\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("          <input type=\"text\" class=\"form-control\" placeholder=\"搜索项目\">\n");
      out.write("          <button type=\"submit\" class=\"btn btn-default\">走你</button>\n");
      out.write("        </div>\n");
      out.write("      </form>-->\n");
      out.write("      <ul class=\"nav navbar-nav navbar-right\" style=\"margin-right: 20px\">\n");
      out.write("        <div class=\"dropdown pull-right\">\n");
      out.write("          <button class=\"btn dropdown-toggle\" type=\"button\" id=\"login-name\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"true\">\n");
      out.write("            我要提交项目\n");
      out.write("            <span class=\"caret\"></span>\n");
      out.write("          </button>\n");
      out.write("          <ul class=\"dropdown-menu\" aria-labelledby=\"dropdownMenu1\">\n");
      out.write("            <li><a href=\"login.jsp\" id=\"login\">提交</a></li>\n");
      out.write("            <li class=\"disabled\"><a href=\"logout.jsp\">注销</a></li>\n");
      out.write("          </ul>\n");
      out.write("        </div>\n");
      out.write("      </ul>\n");
      out.write("    </div>\n");
      out.write("  </nav>\n");
      out.write("  <div id=\"main\">\n");
      out.write("    <div class=\"container\" style=\"\">\n");
      out.write("      <div class=\"row\" style=\"margin-top: 100px\">\n");
      out.write("        <div id=\"vote-result\" class=\"col-lg-10 col-lg-offset-1\" style=\"height: 550px;\">\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("  <!--lottery-modal-->\n");
      out.write("  <div class=\"modal fade\" id=\"lottery-modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\n");
      out.write("    <div class=\"modal-dialog\">\n");
      out.write("      <div class=\"modal-content\">\n");
      out.write("        <div class=\"modal-header\">\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">\n");
      out.write("            &times;\n");
      out.write("          </button>\n");
      out.write("          <h4 class=\"modal-title\" id=\"myModalLabel\">\n");
      out.write("            抽奖\n");
      out.write("         </h4>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"modal-body\" style=\"overflow: hidden\">\n");
      out.write("          <div class=\"col-lg-12\">\n");
      out.write("            <form id=\"form\" class=\"form-horizontal\" role=\"form\">\n");
      out.write("              <div id=\"lottery-user\" class=\"form-group\">\n");
      out.write("                <label class=\"col-sm-2 control-label\">用户名</label>\n");
      out.write("                <div class=\"col-sm-10\">\n");
      out.write("                  <input class=\"textin form-control\" type=\"text\" placeholder=\"用户名\">\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("              <div id=\"lottery-psw\" class=\"form-group\">\n");
      out.write("                <label class=\"col-sm-2 control-label\">密码</label>\n");
      out.write("                <div class=\"col-sm-10\">\n");
      out.write("                  <input class=\"textin form-control\" type=\"text\" placeholder=\"密码\">\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("              <!--<div id=\"lottery-check\" class=\"form-group\">\n");
      out.write("                <label class=\"col-sm-2 control-label\">验证码</label>\n");
      out.write("                <div class=\"col-sm-7\">\n");
      out.write("                  <input class=\"textin form-control\" type=\"text\" placeholder=\"验证码\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-sm-3\" id=\"check-img\"><img src=\"images/win-2.png\"></div>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-sm-12 check-alert alert alert-danger\" role=\"alert\">\n");
      out.write("                你的验证码输入错误！\n");
      out.write("              </div>-->\n");
      out.write("            </form>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"modal-footer\">\n");
      out.write("          <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">关闭\n");
      out.write("          </button>\n");
      out.write("          <button type=\"button\" class=\"btn btn-primary\" data-toggle=\"modal\">\n");
      out.write("            抽奖\n");
      out.write("          </button>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("  <!--lottery-result-->\n");
      out.write("  <div class=\"modal fade\" id=\"lottery-result\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\n");
      out.write("    <div class=\"modal-dialog\">\n");
      out.write("      <div class=\"modal-content\">\n");
      out.write("        <div class=\"modal-header\">\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">\n");
      out.write("            &times;\n");
      out.write("          </button>\n");
      out.write("          <h4 class=\"modal-title\" id=\"myModalLabel\">\n");
      out.write("            抽奖结果\n");
      out.write("         </h4>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"modal-body\" style=\"overflow: hidden\">\n");
      out.write("          <div class=\"col-lg-12 success\">\n");
      out.write("            <div>\n");
      out.write("              恭喜你抽中<span id=\"lo-result\"></span>等奖!\n");
      out.write("            </div>\n");
      out.write("            <label class=\"col-sm-4 address-lab\">请填写收货地址：</label>\n");
      out.write("            <div class=\"col-sm-8 address\">\n");
      out.write("              <input class=\"textin form-control\" type=\"text\" placeholder=\"收货地址\">\n");
      out.write("            </div>\n");
      out.write("            <div style=\"color: red;\">\n");
      out.write("              请认真填写，只有这一次机会！\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"fail\">\n");
      out.write("            很遗憾你没抽中，再接再厉~\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"modal-footer\">\n");
      out.write("          <button type=\"button\" class=\"btn btn-default closeUp\" data-dismiss=\"modal\">关闭\n");
      out.write("          </button>\n");
      out.write("          <button type=\"button\" class=\"btn btn-default lotteryUp\">提交\n");
      out.write("          </button>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("  <script src=\"js/jquery-1.11.1.min.js\"></script>\n");
      out.write("  <script src=\"js/bootstrap.min.js\"></script>\n");
      out.write("  <!-- <script type=\"text/javascript\" src=\"js/vegas.min.js\"></script> -->\n");
      out.write("  <!-- <script type=\"text/javascript\" src=\"js/mock.js\"></script> -->\n");
      out.write("  <script type=\"text/javascript\" src=\"js/echarts.min.js\"></script>\n");
      out.write("  <script src=\"js/index.js\"></script>\n");
      out.write("  <script type=\"text/javascript\">\n");
      out.write("  // 基于准备好的dom，初始化echarts实例\n");
      out.write("  var myChart = echarts.init(document.getElementById('vote-result'));\n");
      out.write("\n");
      out.write("  var option = {\n");
      out.write("    title: {\n");
      out.write("      text: '大创展投票情况',\n");
      out.write("    },\n");
      out.write("    tooltip: {\n");
      out.write("      trigger: 'axis',\n");
      out.write("      axisPointer: {\n");
      out.write("        type: 'shadow'\n");
      out.write("      }\n");
      out.write("    },\n");
      out.write("    grid: {\n");
      out.write("      left: '3%',\n");
      out.write("      right: '4%',\n");
      out.write("      bottom: '3%',\n");
      out.write("      containLabel: true\n");
      out.write("    },\n");
      out.write("    xAxis: {\n");
      out.write("      type: 'value',\n");
      out.write("      boundaryGap: [0, 0.01]\n");
      out.write("    },\n");
      out.write("    yAxis: {\n");
      out.write("      type: 'category',\n");
      out.write("      // data: ['小组1', '小组2', '小组3', '小组4', '小组5', '小组6', '小组5', '小组6', '小组5', '小组6']\n");
      out.write("    },\n");
      out.write("    series: [{\n");
      out.write("        name: '票数',\n");
      out.write("        type: 'bar',\n");
      out.write("        // data: [182, 234, 290, 104, 131, 630, 131, 630, 131, 63]\n");
      out.write("      },\n");
      out.write("    ]\n");
      out.write("  };\n");
      out.write("  // 后台往前端传的json格式就是如下data的格式：\n");
      out.write("  var data = {\n");
      out.write("    /*'小组1': 100,\n");
      out.write("    '小组2': 102,\n");
      out.write("    '小组3': 105,\n");
      out.write("    '小组4': 101,\n");
      out.write("    '小组5': 200,\n");
      out.write("    '小组6': 388,\n");
      out.write("    '小组7': 98,\n");
      out.write("    '小组8': 120,\n");
      out.write("    '小组9': 401,\n");
      out.write("    '小组10': 237*/\n");
      out.write("  };\n");
      out.write("\n");
      out.write("  // 这下面是前端的部分不用关心，只需要关心上面的data格式\n");
      out.write("    option.yAxis.data = [];\n");
      out.write("    option.series[0].data = [];\n");
      out.write("    for(var k in data){\n");
      out.write("      option.yAxis.data.push(k);\n");
      out.write("      option.series[0].data.push(data[k]);\n");
      out.write("    }\n");
      out.write("    myChart.setOption(option);\n");
      out.write("    var chartData = [];\n");
      out.write("    function ajaxData(){\n");
      out.write("    \t$.ajax({\n");
      out.write("    \t\turl:'voterand.action',\n");
      out.write("    \t\tdata:[],\n");
      out.write("    \t\ttype:'get',\n");
      out.write("    \t\tscriptCharset: 'utf-8',\n");
      out.write("    \t\tsuccess: function(data){\n");
      out.write("    \t\tdata = JSON.parse(data);\n");
      out.write("    \t\tfor (var i in data){\n");
      out.write("    \t\t\tvar obj = {};\n");
      out.write("    \t\t\tobj.group = i;\n");
      out.write("    \t\t\tobj.vote = data[i];\n");
      out.write("    \t\t\tchartData.push(obj);\n");
      out.write("    \t\t}\n");
      out.write("    \t\tchartData.sort(function(a,b){\n");
      out.write("    \t\t\treturn a.vote - b.vote\t\n");
      out.write("    \t\t});\n");
      out.write("    \t\toption.yAxis.data = [];\n");
      out.write("    \t\toption.series[0].data = [];\n");
      out.write("    \t\tfor(var k = 0; k < chartData.length; k++){\n");
      out.write("      \t\toption.yAxis.data.push(chartData[k].group);\n");
      out.write("      \t\toption.series[0].data.push(chartData[k].vote);\n");
      out.write("    \t\t}\n");
      out.write("    \t\tmyChart.setOption(option);\n");
      out.write("    \t\tchartData = [];\n");
      out.write("    \t}\n");
      out.write("    \n");
      out.write("  });\n");
      out.write("  }\n");
      out.write("  ajaxData();\n");
      out.write("  setInterval(function(){ajaxData()},60000);\n");
      out.write("  </script>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
