/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2016-05-15 17:16:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import db.fun.*;
import db.pojo.*;

public final class voterand_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <script src=\"js/Chart.js\"> </script>\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("    <title>大创展投票系统</title>\r\n");
      out.write("    <!-- Bootstrap -->\r\n");
      out.write("    <link href=\"css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/bootstrap-theme.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- siimple style -->\r\n");
      out.write("    <link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("    body {\r\n");
      out.write("        background-color: #f6f6f6;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #logo-text,\r\n");
      out.write("    #login {\r\n");
      out.write("        color: #ffffff;\r\n");
      out.write("        font-size: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #logo {\r\n");
      out.write("        padding-top: 5px;\r\n");
      out.write("    }\r\n");
      out.write("    </style>\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("  body{\r\n");
      out.write("    background:url(\"images/7.png\" );\r\n");
      out.write("    background-size:600px 500px;\r\n");
      out.write("    background-position:720px 200px;\r\n");
      out.write("    background-repeat:no-repeat;\r\n");
      out.write("  }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body  >\r\n");
      out.write("    <!-- Fixed navbar -->\r\n");
      out.write("    <div class=\"navbar navbar-inverse navbar-fixed-top\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"navbar-header\">\r\n");
      out.write("                <!--           <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("          </button> -->\r\n");
      out.write("                <a class=\"navbar-brand\" id=\"logo\" href=\"index.jsp\"><img src=\"images/logo.png\" weight=\"48px\" height=\"48px\" /></a>\r\n");
      out.write("                <p class=\"navbar-text\" id=\"logo-text\">InnovationCamp</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"navbar-collapse collapse\">\r\n");
      out.write("                <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("                    <li><a href=\"loginAdmin.jsp\" id=\"login\">login in</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"header\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("            \t<div class=\"col-lg-12\">\r\n");
      out.write("            <h1 class=\"margin-bottom-15\">创展风云榜</h1>\r\n");
      out.write("            <h4>票数</h4>\r\n");
      out.write("            </div>\r\n");
      out.write("\t");

	List l=new FunProjectData().showProjectVote(0,10);
	String[] name=new String[10];	
	Long[] votenum=new Long[10];	
	ProjectData[] p = new ProjectData[10];
	for(int i=0; i<10; i++)
	{
	p[i] = (ProjectData)l.get(i);
	name[i]=p[i].getProjectID();
	votenum[i]=p[i].getVoteNumber();
	//out.print(name[i]);
	//out.print(votenum[i]);
	}	
	
      out.write("\r\n");
      out.write("\t<canvas id=\"myChart\"  width=\"800\" height=\"450\"></canvas>\r\n");
      out.write("\t<script  type=\"text/javascript\">\r\n");
      out.write("\twindow.onload = function ()\r\n");
      out.write("  {\r\n");
      out.write("\tvar ctx = document.getElementById(\"myChart\").getContext(\"2d\");\r\n");
      out.write("\tvar data = {\r\n");
      out.write("\tlabels : [\"");
      out.print(name[0]);
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(name[1]);
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(name[2]);
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(name[3]);
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(name[4]);
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(name[5]);
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(name[6]);
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(name[7]);
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(name[8]);
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(name[9]);
      out.write("\"],\r\n");
      out.write("\tdatasets : [\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tfillColor : \"rgba(020,100,160,40)\",\r\n");
      out.write("\t\t\tstrokeColor : \"rgba(255,255,255,1)\",\r\n");
      out.write("\t\t\tpointColor : \"#3dc448\",\r\n");
      out.write("              pointStrokeColor : \"#fff\",\r\n");
      out.write("\t\t\tdata : [");
      out.print(votenum[0] );
      out.write(',');
      out.print(votenum[1] );
      out.write(',');
      out.print(votenum[2] );
      out.write(',');
      out.print(votenum[3] );
      out.write(',');
      out.print(votenum[4] );
      out.write(',');
      out.print(votenum[5] );
      out.write(',');
      out.print(votenum[6] );
      out.write(',');
      out.print(votenum[7] );
      out.write(',');
      out.print(votenum[8] );
      out.write(',');
      out.print(votenum[9] );
      out.write("]\r\n");
      out.write("\t\t}\r\n");
      out.write("     \t]\r\n");
      out.write("\t}\r\n");
      out.write("\tvar defaults = \r\n");
      out.write("\t{\r\n");
      out.write("\t\tscaleGridLineWidth : 0,\t\r\n");
      out.write("\t\tscaleLineColor : \"rgba(255,255,255,0)\",\r\n");
      out.write("\t\tscaleShowGridLines : false,\r\n");
      out.write("\t\tdatasetFill : true,\r\n");
      out.write("\t\t\r\n");
      out.write("        animation : false,\r\n");
      out.write("\t}\r\n");
      out.write("\tnew Chart(ctx).Bar(data,defaults);                                             \r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("项目编号\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  \r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-1.10.2.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"js/Chart.js\"> </script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
