/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-05-17 15:40:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import db.fun.*;
import db.pojo.*;

public final class zhuzhuangtu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>  \r\n");
      out.write("<title>\\u67F1\\u72B6\\u56FE </title>\r\n");
      out.write("<head> \r\n");
      out.write("<script src=\"js/Chart.js\"> </script>\r\n");
      out.write("//<script src=\"js/jquery-2.1.3.js\"> </script>\r\n");
      out.write("<meta http-equiv=\"refresh\" content=\"20\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

List l=new FunProjectInfo().showProjectVote(0,10);
Long[] name=new Long[10];	
int[] votenum=new int[10];	
ProjectInfo[] p = new ProjectInfo[10];
for(int i=0; i<10; i++)
{
p[i] = (ProjectInfo)l.get(i);

name[i]=p[i].getProjectID();
votenum[i]=p[i].getVoteNum();
//out.print(name[i]);
//out.print(votenum[i]);
 }	

      out.write("\r\n");
      out.write("<canvas id=\"myChart\"  width=\"800\" height=\"400\"></canvas>\r\n");
      out.write("<script  type=\"text/javascript\">\r\n");
      out.write("window.onload = function ()\r\n");
      out.write(" {\r\n");
      out.write("var ctx = document.getElementById(\"myChart\").getContext(\"2d\");\r\n");
      out.write("var data = {\r\n");
      out.write("\tlabels : [\"");
      out.print(name[0]);
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(name[1]);
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(name[2]);
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(name[3]);
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(name[4]);
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(name[5]);
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(name[6]);
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(name[7]);
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(name[8]);
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(name[9]);
      out.write("\"],\r\n");
      out.write("\tdatasets : [\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tfillColor : \"rgba(255,0,0,0.5)\",\r\n");
      out.write("\t\t\tstrokeColor : \"rgba(255,255,255,1)\",\r\n");
      out.write("\t\t\tdata : [");
      out.print(votenum[0]);
      out.write(',');
      out.print(votenum[1]);
      out.write(',');
      out.print(votenum[2]);
      out.write(',');
      out.print(votenum[3]);
      out.write(',');
      out.print(votenum[4]);
      out.write(',');
      out.print(votenum[5]);
      out.write(',');
      out.print(votenum[6]);
      out.write(',');
      out.print(votenum[7]);
      out.write(',');
      out.print(votenum[8]);
      out.write(',');
      out.print(votenum[9]);
      out.write("]\r\n");
      out.write("\t\t}\r\n");
      out.write("     \t]\r\n");
      out.write("}\r\n");
      out.write("new Chart(ctx).Bar(data);                                             //\\u67F1\\u72B6\\u56FE\r\n");
      out.write("/*function test(){\r\n");
      out.write("$.ajax({\r\n");
      out.write("  type: \"get\", \r\n");
      out.write("  url: \"data.txt\", \r\n");
      out.write("  success: function(data){\r\n");
      out.write("    $(\"#localrefresh\")[0].innerHTML=data;\r\n");
      out.write("  }\r\n");
      out.write("});\r\n");
      out.write("}*/\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>  ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
